env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
install:
  - pip install django==${DJANGO}
  - pip install .
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
script: python test_project/manage.py test djangoshpaml_tests
