env:
  global:
    - DJANGO_SETTINGS_MODULE=test_project.settings
  matrix:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
install:
  - pip install django==${DJANGO}
  - pip install .
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
script: python test_project/manage.py test djangoshpaml_tests
